---
replicaCount: 5

image:
  tag: 0.9.1

ingress:
  enabled: true
  hosts:
    - host: echo.company.com
      paths:
        - /
  annotations:
    kubernetes.io/ingress.class: nginx

  application:
    logs:
      ignore:
        ping: true
